#!/bin/bash

# Exit immediately if a pipeline returns non-zero status
# http://www.gnu.org/software/bash/manual/bashref.html#The-Set-Builtin
set -e

npm run verify

if [ -n "$npm_config_major" ]; then SEMVER="major"
elif [ -n "$npm_config_patch" ]; then SEMVER="patch"
else SEMVER="minor"; fi

echo 'Bumping npm version ...'
npm version $SEMVER

echo 'Creating git release tag ...'
github-publish-release

echo 'Pushing git release ...'
git push --follow-tags

echo 'Finished releasing.'
